id: AA905BDCD
title: Prayer to Buddha Amitābha
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.123597
  last_modified_at: 2022-03-01 02:42:41.123600
