id: AA905BDCD
title: A Sukhāvatī Prayer and Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.106592
  last_modified_at: 2022-03-01 02:42:41.106598
