id: AA905BDCD
title: Prayer to Behold Amitābha in Dreams
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.122379
  last_modified_at: 2022-03-01 02:42:41.122382
