id: AA905BDCD
title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
  Light'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.126917
  last_modified_at: 2022-03-01 02:42:41.126919
