id: AA905BDCD
title: Brief Amitābha Sleeping Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.116322
  last_modified_at: 2022-03-01 02:42:41.116325
