id: AA905BDCD
title: Prayer of Aspiration Towards Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.121317
  last_modified_at: 2022-03-01 02:42:41.121320
