id: AA905BDCD
title: Aspiration for the Land of Great Bliss
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.110480
  last_modified_at: 2022-03-01 02:42:41.110483
