id: AA905BDCD
title: Aspiration for Rebirth in Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.109069
  last_modified_at: 2022-03-01 02:42:41.109074
