id: AA905BDCD
title: Aspiration to Be Reborn in the Realm of Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.114375
  last_modified_at: 2022-03-01 02:42:41.114378
