id: AA905BDCD
title: Sukhāvatī Aspiration
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:42:41.125203
  last_modified_at: 2022-03-01 02:42:41.125206
